language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli istanbul
script:
  - npm test --verbose
after_success:
  - istanbul cover jasmine-node tests/ --verbose && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
deploy:
  provider: npm
  email: "sixertoy.github@gmail.com"
  api_key: "5A7k6gniaEyzHr9X7fPC"
  on:
    branch: master
